language: java
jdk:
 - openjdk11

cache:
 directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "alecol1995"
    token:
      secure: "554a5f85b8d0a36d9969a65ed19bb98b98b69240" # encrypted value of your token

jobs:
 include:
  script:
   - mvn clean verify

jobs:
 include:
  if: branch = develop
  script:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

   - docker build -t app-db ./sample-application-db-changelog-job
   - docker tag app-db $DOCKER_USERNAME/app-db
   - docker push $DOCKER_USERNAME/app-db

   - docker build -t app-http ./sample-application-http-api-server
   - docker tag app-http $DOCKER_USERNAME/app-http
   - docker push $DOCKER_USERNAME/app-http
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
