language: java
jdk:
 - openjdk11

cache:
 directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

addons:
 sonarcloud:
  organization: "alecol1995"
   token: "b51a559ab24f0b4c6b29e9bd388d2922355bf1d2" # encrypted value of your token

jobs:
 include:
  script:
   - mvn clean verify

jobs:
 include:
  if: branch = develop
  script:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

   - docker build -t app-db ./sample-application-db-changelog-job
   - docker tag app-db $DOCKER_USERNAME/app-db
   - docker push $DOCKER_USERNAME/app-db

   - docker build -t app-http ./sample-application-http-api-server
   - docker tag app-http $DOCKER_USERNAME/app-http
   - docker push $DOCKER_USERNAME/app-http
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
