language: java
jdk:
 - openjdk11

jobs:
 include:
  script:
   - mvn clean verify

jobs:
 include:
  if: branch = develop
  script:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

   - docker build -t app-db ./sample-application-db-changelog-job
   - docker tag app-db $DOCKER_USERNAME/app-db
   - docker push $DOCKER_USERNAME/app-db

   - docker build -t app-http ./sample-application-http-api-server
   - docker tag app-http $DOCKER_USERNAME/app-http
   - docker push $DOCKER_USERNAME/app-http
